name: Python Application Deployment

on:
  push:
    branches:
      - master  # Ensure it triggers on the master branch
  pull_request:
    branches:
      - master  # Triggers on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up a Python environment
      with:
        python-version: '3.12.0'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrades pip
        pip install -r requirements.txt  # Installs dependencies from requirements.txt

    - name: Run Python script
      run: |
        python main.py  # Runs your Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        Flask_session_key:  ${{ secrets.Flask_session_key}}
