name: Python Application Deployment

on:
  push:
    branches:
      - master  # Ensure it triggers on the master branch
  pull_request:
    branches:
      - master  # Triggers on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up a Python environment
      with:
        python-version: '3.12.0'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrades pip
        pip install -r requirements.txt  # Installs dependencies from requirements.txt

    - name: Run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pytest  # Assumes you have tests to run

    - name: Deploy to Heroku
      run: |
        heroku login -i
        git push heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Run Gunicorn
      run: |
        source venv/bin/activate
        gunicorn main:app
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        Flask_session_key: ${{ secrets.Flask_session_key }}
